name = "pica200"
grammar = "pica200"
path_suffixes = ["pica"]
line_comments = [";"]
autoclose_before = "])"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
]